services:
  model-service:
    image: ghcr.io/doda2025-team21/backend:${TAG_VERSION:-latest}
    container_name: backend
    ports:
      - "8081:8081"
    volumes:
      - ./model:/app/output
    restart: unless-stopped

  app:
    image: ghcr.io/doda2025-team21/frontend:${TAG_VERSION:-latest}
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      # put all your environment variables here
      - MODEL_HOST=http://model-service:8081
    depends_on:
      - model-service
    restart: unless-stopped
    