{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-email-secret
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: alertmanager
    release: {{ .Release.Name }}
type: Opaque
stringData:
  password: {{ .Values.alertmanager.smtp.password | quote }}
{{- end }}