apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            # ---------------------------
            # VALUES ENV VARIABLES (NORMAL)
            # ---------------------------
            - name: APP_PORT
              value: "{{ .Values.app.port }}"
            - name: MODEL_HOST
              value: "http://model-service:{{ .Values.model.port }}"
            # ---------------------------
            # CONFIGMAP ENV VARIABLES
            # ---------------------------
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Values.app.name }}-config"
                  key: WELCOME_MESSAGE
            - name: DUMMY_VALUE
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Values.app.name }}-config"
                  key: DUMMY_VALUE
            # ---------------------------
            # SECRET ENV VARIABLES
            # ---------------------------
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.app.name }}-secret"
                  key: API_KEY

            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.app.name }}-secret"
                  key: PASSWORD
