apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: {{ .Values.app.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.app.ingress.hosts.stable | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  number: {{ .Values.app.port }}
    {{- if .Values.app.ingress.hosts.preview }}
    - host: {{ .Values.app.ingress.hosts.preview | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  number: {{ .Values.app.port }}
    {{- end }}
