apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-traffic-alert
  labels:
    release: {{ .Values.monitoring.prometheusRelease }}
spec:
  groups:
    - name: traffic-alerts
      rules:
        - alert: HighRequestRate
          expr: rate(app_requests_total[1m]) * 60 > 15
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High Request Volume"
            description: "More than 15 requests/min for over 2 minutes."
